version: "3.8"

services:

    elasticsearch:

        container_name: elasticsearch

        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0

        environment:

            - discovery.type=single-node

            - xpack.security.enabled=false

            - bootstrap.memory_lock=true

            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

        ulimits:

            memlock:

                soft: -1

                hard: -1

        volumes:

            - /datadrive/esdata:/usr/share/elasticsearch/data

        restart: unless-stopped

        ports:

            - "9200:9200"

            - "9300:9300"

        networks:

            - efk

        healthcheck:

            test:

                [

                "CMD-SHELL",

                "curl --fail http://localhost:9200 || exit 1",

                ]

            interval: 10s

            timeout: 10s

            retries: 120

    kibana:

        container_name: kibana

        image: docker.elastic.co/kibana/kibana:8.2.0

        environment:

            - ELASTICSEARCH_HOSTS=http://20.225.205.182:9200

        restart: unless-stopped

        ports:

            - "5601:5601"

        networks:

            - efk

        depends_on:

            - elasticsearch

        links:

            - elasticsearch

        healthcheck:

            test:

                [

                "CMD-SHELL",

                "curl --fail http://localhost:5601 || exit 1",

                ]

            interval: 10s

            timeout: 10s

            retries: 120

    grafana:

        image: grafana/rajan:v01

        ports:

            - 3000:3000

        restart: unless-stopped

        networks:

            - efk

        volumes:

                #            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

            - /mnt/grafana-data:/var/lib/grafana

        environment:

            - GF_SMTP_ENABLED=true

            - GF_SMTP_HOST=smtp.gmail.com:587

            - GF_SMTP_USER=

            - GF_SMTP_FROM_ADDRESS=

            - GF_SMTP_PASSWORD=

            - GF_INSTALL_PLUGINS=natel-discrete-panel,bessler-pictureit-panel,grafana-clock-panel,grafana-piechart-panel,neocat-cal-heatmap-panel,petrslavotinek-carpetplot-panel,flant-statusmap-panel,mxswat-separator-panel,michaeldmoore-multistat-panel,savantly-heatmap-panel

volumes:

    grafana-data:

    elasticsearch_data:

networks:

    efk:

